stages:
  - build
  - docker
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  IMAGE_TAG_LATEST: $CI_REGISTRY_IMAGE:latest
  APP_NAME: muvbot
  APP_PORT: 4322

build:
  image: node:20
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - html/

.docker_login: &docker_login
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

docker-build:
  stage: docker
  <<: *docker_login
  script:
    - docker build
        -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
        -t $CI_REGISTRY_IMAGE:latest
        -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
        ./maintenance-page
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

.deploy_base: &deploy_base
  stage: deploy
  image: ubuntu:24.04
  before_script:
    - apt-get update && apt-get install -y openssh-client sshpass
  variables:
    SERVER_IP: 45.81.232.242
    SERVER_USER: root

deploy:
  stage: deploy
  <<: *deploy_base
  script:
    - mkdir -p ~/.ssh
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
    - sshpass -p "$SSH_PASSWORD" ssh $SERVER_USER@$SERVER_IP
        "echo '$DEPLOY_TOKEN_PASSWORD' | docker login -u '$DEPLOY_TOKEN_USER' --password-stdin '$CI_REGISTRY'"
    - sshpass -p "$SSH_PASSWORD" ssh $SERVER_USER@$SERVER_IP
        "docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
    - sshpass -p "$SSH_PASSWORD" ssh $SERVER_USER@$SERVER_IP
        "docker rm -f michael-homepage || true"
    - sshpass -p "$SSH_PASSWORD" ssh $SERVER_USER@$SERVER_IP
        "docker run -d --name michael-homepage -p 8081:80 --restart unless-stopped $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
